#!/sbin/runscript

set_phpvars() {
	PHPSLOT=${SVCNAME#php-fpm-}
	[ ${PHPSLOT} = 'php-fpm' ] && PHPSLOT="$(eselect php show fpm)"

	PHP_FPM_CONF="/etc/php/fpm-${PHPSLOT}/php-fpm.conf"
	PHP_FPM_PID="/var/run/php-fpm-${PHPSLOT}.pid"
	PHP_FPM_SOCK_DIR="/var/run/${PHPSLOT}-fpm"
	PHP_FPM_CHROOT="/var/lib/${PHPSLOT}-fpm/chroot"
}

extra_commands="depend"
extra_started_commands="reload"

depend() {
	need net
	use apache2 lighttpd nginx
}

_mount() {
	local from
	local to
	local opts
	local ret=0

	if [ "${#}" -lt 3 ]; then
		eerror "_mount(): to few arguments"
		return 1
	fi

	from=$1
	to=$2
	shift 2

	opts="${*}"
	shift $#

	if [ -z "$(awk "\$2 == \"${to}\" { print \$2 }" /proc/mounts)" ]; then
		einfo "mounting ${from} to ${to}"
		mount ${from} ${to} ${opts}
		ret=$?

		eend $ret
		return $ret
	fi

	return 0
}

_umount() {
	local dir=$1
	local ret=0

	if [ -n "$(awk "\$2 == \"${dir}\" { print \$2 }" /proc/mounts)" ]; then
		ebegin "umounting ${dir}"
		umount ${dir}
		ret=$?

		eend $ret
		return $ret
	fi

	return 0
}

create_chroot() {
	[ -d "${PHP_FPM_CHROOT}/dev" ] || mkdir -p "${PHP_FPM_CHROOT}/dev"
	[ -d "${PHP_FPM_CHROOT}/etc" ] || mkdir "${PHP_FPM_CHROOT}/etc"
	[ -d "${PHP_FPM_CHROOT}/tmp" ] || mkdir "${PHP_FPM_CHROOT}/tmp" && chmod +t,o+w "${PHP_FPM_CHROOT}/tmp"
	[ -d "${PHP_FPM_CHROOT}/var/www" ] || mkdir -p "${PHP_FPM_CHROOT}/var/www"
	[ -d "${PHP_FPM_CHROOT}/lib64" ] || mkdir "${PHP_FPM_CHROOT}/lib64"
	[ -c "${PHP_FPM_CHROOT}/dev/null" ] || mknod "${PHP_FPM_CHROOT}/dev/null" c 1 3 && chmod 666 "${PHP_FPM_CHROOT}/dev/null"
	[ -c "${PHP_FPM_CHROOT}/dev/random" ] || mknod "${PHP_FPM_CHROOT}/dev/random" c 1 8 && chmod 666 "${PHP_FPM_CHROOT}/dev/random"
	[ -c "${PHP_FPM_CHROOT}/dev/urandom" ] || mknod "${PHP_FPM_CHROOT}/dev/urandom" c 1 9 && chmod 666 "${PHP_FPM_CHROOT}/dev/urandom"
	[ -f "${PHP_FPM_CHROOT}/etc/localtime" ] || ln /etc/localtime "${PHP_FPM_CHROOT}/etc"
	[ -f "${PHP_FPM_CHROOT}/etc/resolv.conf" ] || ln /etc/resolv.conf "${PHP_FPM_CHROOT}/etc"
	[ -f "/etc/ImageMagick-6/delegates.xml" ] && mkdir -p "${PHP_FPM_CHROOT}/etc/ImageMagick-6/" &&  cp "/etc/ImageMagick-6/delegates.xml" "${PHP_FPM_CHROOT}/etc/ImageMagick-6/delegates.xml"
	LIBS=('/lib64/libnss_dns.so.2' '/lib64/libnss_files.so.2')
	LIBS+=(`lddtree /usr/bin/php-fpm | awk '$3 ~ /^\.?\// {print $3}'`)
	LIBS+=(`lddtree /usr/lib/${PHPSLOT}/lib/extensions/no-debug-non-zts-*/* | awk '/^\W/ && $3 ~ /^\.?\// {print $3}'`)
	LIBS+=(`lddtree /usr/lib64/ImageMagick-*/modules-Q16/coders/pdf.so | awk '$3 ~ /^\.?\// {print $3}'`)

	# if imagemagick
	IMAGICK=`awk 'match($0,/command="(&quot;)?([a-zA-Z]+)(&quot;)? .*"/,m) { print m[2] }' /etc/ImageMagick-6/delegates.xml | sort -u`
	echo "${IMAGICK[@]}" | while read line
	do
		WHICH=`which $line 2> /dev/null`
		if [ "$WHICH" != "which:*" ]; then
			LIBS+=(`lddtree $WHICH`)
		fi
	done

	LIBS2=($(for each in ${LIBS[@]}; do echo $each; done | sort -u))
	for lib in "${LIBS2[@]}"
	do
		[ -z "${lib}" ] && continue
		if [ ! -f "${PHP_FPM_CHROOT}${lib}" ] || [ "$lib" -nt "${PHP_FPM_CHROOT}${lib}" ]; then
			ebegin "Copying $lib to chroot"
			mkdir -p `dirname "${PHP_FPM_CHROOT}$lib"`
			cp -p -P "$lib" "${PHP_FPM_CHROOT}${lib}"
			while [ -L "$lib" ] && [ ! -e "${PHP_FPM_CHROOT}$lib" ]; do
				lib=`dirname "$lib"`/`readlink "$lib"`
				mkdir -p `dirname "${PHP_FPM_CHROOT}$lib"`
				cp -p -P "$lib" "${PHP_FPM_CHROOT}$lib"
			done;
			eend $?
		fi
	done

	[ -d "${PHP_FPM_CHROOT}/usr/share/php" ] || mkdir -p "${PHP_FPM_CHROOT}/usr/share/php"
	[ -f "${PHP_FPM_CHROOT}/usr/sbin/sendmail" ] || mkdir -p "${PHP_FPM_CHROOT}/usr/sbin" && cp /usr/sbin/sendmail "${PHP_FPM_CHROOT}/usr/sbin/sendmail"
	[ -d "${PHP_FPM_CHROOT}/usr/lib/ImageMagick-6.8.8" ] || mkdir -p "${PHP_FPM_CHROOT}/usr/lib/ImageMagick-6.8.8"
	[ -e "${PHP_FPM_CHROOT}/usr/lib64" ] || ln -s lib "${PHP_FPM_CHROOT}/usr/lib64"
	grep -qs "${PHP_FPM_CHROOT}/var/www" /proc/mounts || _mount /var/www "${PHP_FPM_CHROOT}/var/www" -o bind
	grep -qs "${PHP_FPM_CHROOT}/usr/share/php" /proc/mounts || _mount /usr/share/php "${PHP_FPM_CHROOT}/usr/share/php" -o bind
	grep -qs "${PHP_FPM_CHROOT}/usr/lib/ImageMagick-6.8.8" /proc/mounts || _mount /usr/lib/ImageMagick-6.8.8 "${PHP_FPM_CHROOT}/usr/lib/ImageMagick-6.8.8" -o bind
	#_mount /usr/share/zoneinfo 
}

stop_chroot() {
	grep -qs "${PHP_FPM_CHROOT}/var/www" /proc/mounts && _umount "${PHP_FPM_CHROOT}/var/www"
	grep -qs "${PHP_FPM_CHROOT}/usr/share/php" /proc/mounts && _umount "${PHP_FPM_CHROOT}/usr/share/php"
	grep -qs "${PHP_FPM_CHROOT}/usr/lib/ImageMagick-6.8.8" /proc/mounts && _umount "${PHP_FPM_CHROOT}/usr/lib/ImageMagick-6.8.8"
}

start() {
        ebegin "Starting PHP FastCGI Process Manager"
	set_phpvars

	if [ ! -d "${PHP_FPM_SOCK_DIR}" ]; then
		mkdir "${PHP_FPM_SOCK_DIR}"
		rc=$?
		if  [ $rc -ne 0 ]; then
			eerror "Directory ${PHP_FPM_SOCK_DIR} for sockets does not exist and cannot be created"
			return 1
		fi
	fi

	create_chroot
	ulimit -c unlimited

        #start-stop-daemon --start --pidfile ${PHP_FPM_PID} -e MAGICKCODERMODULE_PATH=/usr/lib/ImageMagick-6.8.6/modules-Q16/coders --exec \
	start-stop-daemon --start --pidfile ${PHP_FPM_PID} --exec \
            /usr/lib/${PHPSLOT}/bin/php-fpm -- -y "${PHP_FPM_CONF}" -g "${PHP_FPM_PID}"
        local i=0
        local timeout=5
        while [ ! -f ${PHP_FPM_PID} ] && [ $i -le $timeout ]; do
            sleep 1
            i=$(($i + 1))
        done
        
        [ $timeout -gt $i ]
        eend $?
}

stop() {
        ebegin "Stopping PHP FastCGI Process Manager"
	local ret
	set_phpvars
        start-stop-daemon --signal QUIT --stop --exec /usr/lib/${PHPSLOT}/bin/php-fpm --pidfile ${PHP_FPM_PID}
	ret=$?
	[ $ret -eq 0 ] && stop_chroot
        eend $ret
}

reload() {
    ebegin "Reloading PHP FastCGI Process Manager"
    set_phpvars
    [ -f ${PHP_FPM_PID} ] && kill -USR2 $(cat ${PHP_FPM_PID})
    eend $?
}
